### ISSUE TITLE
'twitter' gems (pre 4.0) have been yanked -> breaks 'stratify-twitter'

### ISSUE THREAD

**Issue by epitron** [jasonrudolph/stratify#3]
Just a heads up! :)

**Comment by jasonrudolph** [comment]
Thanks for opening this issue.

To fix this issue, stratify-twitter needs to upgrade to a newer version of the twitter gem, _and_ it needs to authorize via OAuth. (The current stratify-twitter code does not perform any authentication, since it wasn't previously required if you only wanted to read public data.)

**Comment by jmburges** [comment]
So as of right now the twitter parts of stratify are broken?

**Comment by jmburges** [comment]
Pondering how to refactor the code to handle an oauth handshake. Any ideas? I could just have two fields for the token and token_secret but that requires a lot on the user. I'd prefer not to refactor all the create/new code but that may be required but I can't think of a good way to do it.

**Comment by jasonrudolph** [comment]
> So as of right now the twitter parts of stratify are broken?

stratify-twitter currently [depends on 2.1.x of the twitter gem](https://github.com/jasonrudolph/stratify/blob/37b15bdb0449fab3bb15fb12bc48a47bdbca99ff/stratify-twitter/stratify-twitter.gemspec#L26). The Gemfile is [locked to v2.1.1](https://github.com/jasonrudolph/stratify/blob/37b15bdb0449fab3bb15fb12bc48a47bdbca99ff/stratify-rails/Gemfile.lock#L245). That gem has been removed from rubygems.org. So, when you try to run `bundle install`, it fails.

If you happen to have a copy of v2.1.1 of the twitter gem, stratify-twitter still works fine (for now). Since Twitter API v1.1 requires OAuth, and since stratify-twitter doesn't currently use OAuth, I expect stratify-twitter to stop working in the near future.

We'll likely need to update stratify-twitter to support OAuth and upgrade to the latest version of the twitter gem.

**Comment by jasonrudolph** [comment]
> Pondering how to refactor the code to handle an oauth handshake. Any ideas? I could just have two fields for the token and token_secret but that requires a lot on the user

Moving forward, it's likely that a lot of Stratify collectors will need OAuth. (stratify-foursquare already uses an OAuth token, but the [implementation](https://github.com/jasonrudolph/stratify/blob/37b15bdb0449fab3bb15fb12bc48a47bdbca99ff/stratify-foursquare/lib/stratify-foursquare/collector.rb#L8) leaves a lot to be desired.)

I wonder if we could have a generic OAuth mixin that can be included in any `Stratify::Collector` subclass. I'm not sure that this is the way to go, but it's the first thing I would try.

**Comment by jmburges** [comment]
I feel like an OAuth Mixin would be a reasonable way to do it but the mixin would have to change the way the controller acts. Instead of the flow just being collector/new, enter fields, POST to collector/create. It will be collector/new which redirects somewhere then response to GET of some other action.

**Comment by jasonrudolph** [comment]
Stratify [now](https://github.com/jasonrudolph/stratify/compare/9b5186b...1ada75948b) uses the latest version of the twitter gem (v4.6.2). That should resolve this issue. If you still encounter problems setting up Stratify, please let me know.

When you set up a Twitter collector in the Stratify UI, the instructions will guide you to register your instance of Stratify on dev.twitter.com and [generate an OAuth access token](https://dev.twitter.com/docs/auth/tokens-devtwittercom). Then, you can use those credentials to set up your Twitter collector. Using this approach, we avoid the [complexity associated with implementing the OAuth handshake](https://github.com/jasonrudolph/stratify/issues/3#issuecomment-17619848) (which is really overkill for Stratify's needs).
